--let g:tokyonight_style = "night"

require("enigama.options")
require("enigama.notify")
require("enigama.keymaps")
require("enigama.lazy")
require("enigama.copilot")
-- require("enigama.plugins")
-- require("enigama.cybu")
require("enigama.autocommands")
require("enigama.colorscheme")
-- require("enigama.whichkey")
require("enigama.session")
require("enigama.cmp")
require("enigama.smoothie")
require("enigama.lsp")
require("enigama.lspsaga")
require("enigama.telescope")
require("enigama.treesitter")
require("enigama.autopairs")
-- require("enigama.comment")
require("enigama.gitsigns")
require("enigama.tree")
-- require("enigama.oil")
require("enigama.lualine")
require("enigama.impatient")
require("enigama.harpoon")
require("enigama.toggleterm")
require("enigama.dap")
require("enigama.bqf")
-- require("enigama.scrollbar")
require("enigama.fidget")
require("enigama.colorhighlight")
require("enigama.jester")
require("enigama.neotest")
require("enigama.aerial")
require("enigama.todo-comments")
-- require("enigama.hardtime")
require("enigama.lab")
require("enigama.goto-preview")
require("enigama.indent")
require("enigama.interface-preview")
require("enigama.cmd-noice")
require("enigama.flesh-navi-search")
