--let g:tokyonight_style = "night"

require("enigama.options")
require("enigama.keymaps")
require("enigama.plugins")
require("enigama.autocommands")
require("enigama.colorscheme")
require("enigama.cmp")
require("enigama.lsp")
require("enigama.telescope")
require("enigama.treesitter")
require("enigama.autopairs")
require("enigama.comment")
require("enigama.gitsigns")
require("enigama.nvim-tree")
require("enigama.lualine")
require("enigama.impatient")
require("enigama.harpoon")
require("enigama.toggleterm")
require("enigama.dap")
